[package]
name = "shadex-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
nom = "8.0.0"
rpds = "1.2.0"
rspirv = "0.12.0"
wgpu = { version = "27.0.1", features = ["webgl"] }
wgsl-parse = "0.3.1"
